# Generated by Django 4.0.3 on 2023-12-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('주기없음', '주기없음'), ('매일', '매일'), ('매주', '매주'), ('매월', '매월')], default='주기없음', max_length=10, null=True)),
                ('day', models.CharField(blank=True, max_length=100, null=True)),
                ('week', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
