# Generated by Django 4.0.3 on 2023-12-24 04:37

from django.db import migrations, models
import django.db.models.deletion
import teams.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(choices=[('독서모임', '독서모임'), ('합평모임', '합평모임'), ('책집필모임', '책집필모임')], max_length=10)),
                ('is_closed', models.BooleanField(default=False)),
                ('location', models.TextField(blank=True, null=True)),
                ('max_attendance', models.IntegerField()),
                ('current_attendance', models.IntegerField(default=0)),
                ('introduce', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=teams.models.team_thumbnail_path)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
