# Generated by Django 4.0.3 on 2023-12-24 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatrooms', '0001_initial'),
        ('chatroom_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommessage',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatrooms.chatroom'),
        ),
    ]
